name: Website
on:
  push:
    branches: ["main"]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  run:
    name: Build & Update Website
    if: github.repository == 'EmulatorJS/emulatorjs.org'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          git pull
          yarn install
          yarn build
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.SSH_CDN_PRIVATE_KEY}}" > ~/.ssh/id_ed25519
          echo "Host ${{ secrets.SSH_HOST }}" > ~/.ssh/config
          echo "  User ${{ secrets.SSH_CDN_USERNAME }}" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/id_ed25519" >> ~/.ssh/config
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Update Website
        run: |
          rsync -az --delete -e "ssh -i ~/.ssh/id_ed25519" .output/ ${{ secrets.SSH_CDN_USERNAME}}@${{secrets.SSH_HOST}}:/mnt/HDD/website/emulatorjs.org/
      - name: Restart Website
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.SSH_CDN_USERNAME }}@${{ secrets.SSH_HOST }} "systemctl restart emulatorjs-org"
