name: Website
on:
  push:
    branches: ["main"]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    name: Build
    if: github.repository == 'EmulatorJS/emulatorjs.org'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          git pull
          yarn install
          yarn build
      - name: Zip Website
        run: |
          zip -r website.zip .output/
      - name: Upload Website
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: website.zip
          retention-days: 1

  run:
    name: Deploy
    needs: build
    if: github.repository == 'EmulatorJS/emulatorjs.org'
    runs-on: emulatorjs-server
    steps:
      - name: Download Website
        uses: actions/download-artifact@v4
        with:
          name: website
      - name: Unzip Website
        run: |
          unzip -o website.zip -d output/
      - name: Update Website
        run: |
          rsync -a --delete output/.output/ /mnt/HDD/website/emulatorjs.org/
      - name: Restart Website
        run: |
          systemctl restart emulatorjs-org
      - name: Cleanup
        run: |
          rm -rf output/
          rm -f website.zip
