name: Website
on:
  push:
    branches: ["main"]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  run:
    name: Build & Update Website
    if: github.repository == 'EmulatorJS/emulatorjs.org'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          git pull
          yarn install
          yarn build
      - name: Setup SSH
        run: |
          echo "${{secrets.SSH_CDN_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          echo "Host ${{ secrets.SSH_HOST }}" > ~/.ssh/config
          echo "  User ${{ secrets.SSH_CDN_USERNAME }}" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
          chmod 600 ~/.ssh/id_rsa
      - name: Update Website
        run: |
          rsync -Pavz --delete -e "ssh -i $HOME/.ssh/id_rsa" .output/ ${{ secrets.SSH_CDN_USERNAME}}@${{secrets.SSH_HOST}}:/mnt/HDD/website/emulatorjs.org/
      - name: Restart Website
        run: |
          ssh -i $HOME/.ssh/id_rsa ${{ secrets.SSH_CDN_USERNAME }}@${{ secrets.SSH_HOST }} "systemctl restart emulatorjs-org"
